# Generated by Django 3.2.9 on 2021-12-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_mbe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
